[phases.setup]
nixPkgs = ['python39', 'postgresql']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
]

[phases.build]
cmds = [
    'python manage.py migrate --noinput',
    'python manage.py collectstatic --noinput',
]

[start]
cmd = 'python manage.py runserver 0.0.0.0:$PORT'