[phases.setup]
nixPkgs = ['python39', 'postgresql']
aptPkgs = ['postgresql-client']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
]

[phases.build]
cmds = [
    'python manage.py migrate --noinput',
    'python manage.py setup_initial_data',
    'python manage.py collectstatic --noinput',
]

[start]
cmd = 'gunicorn bloodbankmanagement.wsgi:application --bind 0.0.0.0:$PORT --workers 3'
