services:
  - type: web
    name: bloodbank-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py shell -c "
      from django.contrib.auth.models import User, Group;
      from blood.models import Stock;
      from emergency.models import EmergencyHospital, EmergencyBloodStock;
      
      # Create groups
      Group.objects.get_or_create(name='DONOR')
      Group.objects.get_or_create(name='PATIENT')
      
      # Create admin if doesn't exist
      if not User.objects.filter(username='admin').exists():
          User.objects.create_superuser('admin', 'admin@bloodbank.com', 'admin123')
          print('Admin created: admin/admin123')
      
      # Initialize blood stock
      if not Stock.objects.exists():
          for bg in ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']:
              Stock.objects.create(bloodgroup=bg, unit=15)
          print('Blood stock initialized')
      
      # Load sample hospitals
      if not EmergencyHospital.objects.exists():
          hospitals = [
              {'name': 'King Edward Memorial Hospital', 'address': 'Parel, Mumbai', 'phone': '+912224136051', 'emergency_phone': '+912224136000', 'email': 'kem@hospital.gov.in', 'latitude': 19.0330, 'longitude': 72.8427},
              {'name': 'Tata Memorial Hospital', 'address': 'Parel, Mumbai', 'phone': '+912224177000', 'emergency_phone': '+912224177111', 'email': 'tmc@tmc.gov.in', 'latitude': 19.0176, 'longitude': 72.8562},
              {'name': 'Sion Hospital', 'address': 'Sion, Mumbai', 'phone': '+912224076051', 'emergency_phone': '+912224076000', 'email': 'sion@hospital.gov.in', 'latitude': 19.0433, 'longitude': 72.8639},
              {'name': 'JJ Hospital', 'address': 'Byculla, Mumbai', 'phone': '+912223735555', 'emergency_phone': '+912223735000', 'email': 'jj@hospital.gov.in', 'latitude': 18.9736, 'longitude': 72.8323},
              {'name': 'Nair Hospital', 'address': 'Mumbai Central', 'phone': '+912223027643', 'emergency_phone': '+912223027600', 'email': 'nair@hospital.gov.in', 'latitude': 18.9694, 'longitude': 72.8186},
          ]
          for h_data in hospitals:
              hospital = EmergencyHospital.objects.create(**h_data)
              for bg in ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']:
                  EmergencyBloodStock.objects.create(hospital=hospital, blood_group=bg, units_available=10)
          print('Sample hospitals loaded')
      "
      gunicorn bloodbankmanagement.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: "production"
      - key: SIMULATE_SMS
        value: "True"

databases:
  - name: bloodbank-db
    databaseName: bloodbank
    user: bloodbank