# Generated by Django 4.2.16 on 2025-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyanalytics',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Twilio account balance in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emergencyanalytics',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or system messages'),
        ),
        migrations.AddField(
            model_name='emergencyanalytics',
            name='sms_credits_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate SMS credits remaining', null=True),
        ),
    ]
